//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/InputActions/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Controls"",
            ""id"": ""97953a47-b1a1-429c-bb42-9c02b114e394"",
            ""actions"": [
                {
                    ""name"": ""Touch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cddaf6ad-90e5-4d14-858b-031e39289677"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestTouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5d53b99c-77ec-45e0-b8cb-1826468a54b9"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TestTouch2"",
                    ""type"": ""Value"",
                    ""id"": ""434a5d08-1575-467f-98b9-3add37197fe0"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9bb6a572-f6d5-4e5c-aa42-45fc07ce24a2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa9abfb1-cba8-4ac0-b285-b2259c6d01f5"",
                    ""path"": ""<Touchscreen>/touch0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82a70a15-7626-4c28-95b3-1d09ab63486e"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TestTouch2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DebugButtons"",
            ""id"": ""a43da25d-a420-466f-8275-a029257c6b3d"",
            ""actions"": [
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""2a977dc5-da89-4be3-b9f4-7a0c184b6885"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetScore"",
                    ""type"": ""Button"",
                    ""id"": ""26989c63-9c36-40cb-9cc0-6f4006feffe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadMainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""421c53c6-6542-4de0-8268-207bd33f76f0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReloadCurrentScene"",
                    ""type"": ""Button"",
                    ""id"": ""32487377-fc10-4866-861b-d31452d079bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DestroyBalls"",
                    ""type"": ""Button"",
                    ""id"": ""4db182f4-b999-42c1-bc88-7578ce9e630e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableEventSystem"",
                    ""type"": ""Button"",
                    ""id"": ""30d34f4c-feba-42ce-8bc2-384f5417e833"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5be8b327-85c9-4b25-a4db-b92f8c61a573"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d34aa831-9e65-40df-9c56-9690d364ccfc"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetScore"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7353ad55-986b-40d2-8ac8-888908c19976"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7a051b8-194d-4922-ac89-2a00135b8f4b"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReloadCurrentScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""765109f5-2b00-4407-9015-4aeea66e07c3"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DestroyBalls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9388dfa1-509c-4541-b5f0-8c102c3af01a"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableEventSystem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Controls
        m_Controls = asset.FindActionMap("Controls", throwIfNotFound: true);
        m_Controls_Touch = m_Controls.FindAction("Touch", throwIfNotFound: true);
        m_Controls_TestTouch = m_Controls.FindAction("TestTouch", throwIfNotFound: true);
        m_Controls_TestTouch2 = m_Controls.FindAction("TestTouch2", throwIfNotFound: true);
        // DebugButtons
        m_DebugButtons = asset.FindActionMap("DebugButtons", throwIfNotFound: true);
        m_DebugButtons_Escape = m_DebugButtons.FindAction("Escape", throwIfNotFound: true);
        m_DebugButtons_ResetScore = m_DebugButtons.FindAction("ResetScore", throwIfNotFound: true);
        m_DebugButtons_LoadMainMenu = m_DebugButtons.FindAction("LoadMainMenu", throwIfNotFound: true);
        m_DebugButtons_ReloadCurrentScene = m_DebugButtons.FindAction("ReloadCurrentScene", throwIfNotFound: true);
        m_DebugButtons_DestroyBalls = m_DebugButtons.FindAction("DestroyBalls", throwIfNotFound: true);
        m_DebugButtons_DisableEventSystem = m_DebugButtons.FindAction("DisableEventSystem", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controls
    private readonly InputActionMap m_Controls;
    private List<IControlsActions> m_ControlsActionsCallbackInterfaces = new List<IControlsActions>();
    private readonly InputAction m_Controls_Touch;
    private readonly InputAction m_Controls_TestTouch;
    private readonly InputAction m_Controls_TestTouch2;
    public struct ControlsActions
    {
        private @PlayerInputActions m_Wrapper;
        public ControlsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Touch => m_Wrapper.m_Controls_Touch;
        public InputAction @TestTouch => m_Wrapper.m_Controls_TestTouch;
        public InputAction @TestTouch2 => m_Wrapper.m_Controls_TestTouch2;
        public InputActionMap Get() { return m_Wrapper.m_Controls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsActions set) { return set.Get(); }
        public void AddCallbacks(IControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Add(instance);
            @Touch.started += instance.OnTouch;
            @Touch.performed += instance.OnTouch;
            @Touch.canceled += instance.OnTouch;
            @TestTouch.started += instance.OnTestTouch;
            @TestTouch.performed += instance.OnTestTouch;
            @TestTouch.canceled += instance.OnTestTouch;
            @TestTouch2.started += instance.OnTestTouch2;
            @TestTouch2.performed += instance.OnTestTouch2;
            @TestTouch2.canceled += instance.OnTestTouch2;
        }

        private void UnregisterCallbacks(IControlsActions instance)
        {
            @Touch.started -= instance.OnTouch;
            @Touch.performed -= instance.OnTouch;
            @Touch.canceled -= instance.OnTouch;
            @TestTouch.started -= instance.OnTestTouch;
            @TestTouch.performed -= instance.OnTestTouch;
            @TestTouch.canceled -= instance.OnTestTouch;
            @TestTouch2.started -= instance.OnTestTouch2;
            @TestTouch2.performed -= instance.OnTestTouch2;
            @TestTouch2.canceled -= instance.OnTestTouch2;
        }

        public void RemoveCallbacks(IControlsActions instance)
        {
            if (m_Wrapper.m_ControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlsActions @Controls => new ControlsActions(this);

    // DebugButtons
    private readonly InputActionMap m_DebugButtons;
    private List<IDebugButtonsActions> m_DebugButtonsActionsCallbackInterfaces = new List<IDebugButtonsActions>();
    private readonly InputAction m_DebugButtons_Escape;
    private readonly InputAction m_DebugButtons_ResetScore;
    private readonly InputAction m_DebugButtons_LoadMainMenu;
    private readonly InputAction m_DebugButtons_ReloadCurrentScene;
    private readonly InputAction m_DebugButtons_DestroyBalls;
    private readonly InputAction m_DebugButtons_DisableEventSystem;
    public struct DebugButtonsActions
    {
        private @PlayerInputActions m_Wrapper;
        public DebugButtonsActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Escape => m_Wrapper.m_DebugButtons_Escape;
        public InputAction @ResetScore => m_Wrapper.m_DebugButtons_ResetScore;
        public InputAction @LoadMainMenu => m_Wrapper.m_DebugButtons_LoadMainMenu;
        public InputAction @ReloadCurrentScene => m_Wrapper.m_DebugButtons_ReloadCurrentScene;
        public InputAction @DestroyBalls => m_Wrapper.m_DebugButtons_DestroyBalls;
        public InputAction @DisableEventSystem => m_Wrapper.m_DebugButtons_DisableEventSystem;
        public InputActionMap Get() { return m_Wrapper.m_DebugButtons; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugButtonsActions set) { return set.Get(); }
        public void AddCallbacks(IDebugButtonsActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugButtonsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugButtonsActionsCallbackInterfaces.Add(instance);
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
            @ResetScore.started += instance.OnResetScore;
            @ResetScore.performed += instance.OnResetScore;
            @ResetScore.canceled += instance.OnResetScore;
            @LoadMainMenu.started += instance.OnLoadMainMenu;
            @LoadMainMenu.performed += instance.OnLoadMainMenu;
            @LoadMainMenu.canceled += instance.OnLoadMainMenu;
            @ReloadCurrentScene.started += instance.OnReloadCurrentScene;
            @ReloadCurrentScene.performed += instance.OnReloadCurrentScene;
            @ReloadCurrentScene.canceled += instance.OnReloadCurrentScene;
            @DestroyBalls.started += instance.OnDestroyBalls;
            @DestroyBalls.performed += instance.OnDestroyBalls;
            @DestroyBalls.canceled += instance.OnDestroyBalls;
            @DisableEventSystem.started += instance.OnDisableEventSystem;
            @DisableEventSystem.performed += instance.OnDisableEventSystem;
            @DisableEventSystem.canceled += instance.OnDisableEventSystem;
        }

        private void UnregisterCallbacks(IDebugButtonsActions instance)
        {
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
            @ResetScore.started -= instance.OnResetScore;
            @ResetScore.performed -= instance.OnResetScore;
            @ResetScore.canceled -= instance.OnResetScore;
            @LoadMainMenu.started -= instance.OnLoadMainMenu;
            @LoadMainMenu.performed -= instance.OnLoadMainMenu;
            @LoadMainMenu.canceled -= instance.OnLoadMainMenu;
            @ReloadCurrentScene.started -= instance.OnReloadCurrentScene;
            @ReloadCurrentScene.performed -= instance.OnReloadCurrentScene;
            @ReloadCurrentScene.canceled -= instance.OnReloadCurrentScene;
            @DestroyBalls.started -= instance.OnDestroyBalls;
            @DestroyBalls.performed -= instance.OnDestroyBalls;
            @DestroyBalls.canceled -= instance.OnDestroyBalls;
            @DisableEventSystem.started -= instance.OnDisableEventSystem;
            @DisableEventSystem.performed -= instance.OnDisableEventSystem;
            @DisableEventSystem.canceled -= instance.OnDisableEventSystem;
        }

        public void RemoveCallbacks(IDebugButtonsActions instance)
        {
            if (m_Wrapper.m_DebugButtonsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugButtonsActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugButtonsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugButtonsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugButtonsActions @DebugButtons => new DebugButtonsActions(this);
    public interface IControlsActions
    {
        void OnTouch(InputAction.CallbackContext context);
        void OnTestTouch(InputAction.CallbackContext context);
        void OnTestTouch2(InputAction.CallbackContext context);
    }
    public interface IDebugButtonsActions
    {
        void OnEscape(InputAction.CallbackContext context);
        void OnResetScore(InputAction.CallbackContext context);
        void OnLoadMainMenu(InputAction.CallbackContext context);
        void OnReloadCurrentScene(InputAction.CallbackContext context);
        void OnDestroyBalls(InputAction.CallbackContext context);
        void OnDisableEventSystem(InputAction.CallbackContext context);
    }
}
